name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  lint-and-test:
    name: Lint and Test FastAuth
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      # Step 3: Install Hatch
      - name: Install Hatch
        run: |
          python -m pip install --upgrade pip
          pip install hatch

      # Step 4: Run linter
      - name: Run linter
        run: |
          hatch fmt fastauth

      # Step 5: Run pytest
      - name: Run Pytest
        run: |
          hatch test -c -vv

      # Step 7: Upload Coverage Report
      - name: Upload Coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: Upload test results to Codecov
        if: ${{ !cancelled() }}
        uses: codecov/test-results-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
