name: Python Package CI/CD

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  release:
    types:
      - created

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10' # Вкажіть потрібну версію Python

      # Install Poetry
      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          echo "::add-path::${HOME}/.local/bin"

      # Install dependencies
      - name: Install dependencies
        run: |
          poetry install --no-interaction --no-root

      # Run tests
      - name: Run tests
        run: |
          poetry run pytest

  release:
    needs: test
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # Install Poetry
      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          echo "::add-path::${HOME}/.local/bin"

      # Install dependencies
      - name: Install dependencies
        run: |
          poetry install --no-interaction --no-root

      # Build the package
      - name: Build package
        run: |
          poetry build

      # Publish to PyPI
      - name: Publish to PyPI
        env:
          PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}
        run: |
          poetry publish --username __token__ --password $PYPI_TOKEN
